[project]
name = "optimism-schedule"
authors = ["Optimism Dev Team"]
description = "A smart contract for scheduling and tracking time-based commitments on Stacks"
telemetry = false
requirements = []

[contracts.optimism-core]
path = "contracts/optimism-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
